server:
  port: 8080

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    gateway:
      # Bật auto-discovery route từ Eureka
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: cinema-service
        url: /cinema-service/v3/api-docs
      - name: movie-service
        url: /movie-service/v3/api-docs
      - name: media-service
        url: /media-service/v3/api-docs
      - name: content-service
        url: /content-service/v3/api-docs
      - name: booking-service
        url: /booking-service/v3/api-docs
      - name: communication-service
        url: /communication-service/v3/api-docs

minhnb:
  jwt:
    base64-secret: Muw9kQMoEFTnfKm5sHbvqus3GvSYF4mSCL3ay11sjkRGLpMnvBTpsRF/bDHZmuI5ROhJ23QuZhOb1Cx3OZxy0w==
    access-token-validity-in-seconds: 1800
    refresh-token-validity-in-seconds: 2592000

security:
  whitelist:
    - /auth-service/api/v1/auth/login
    - /auth-service/api/v1/auth/register
    - /auth-service/api/v1/auth/register-request
    - /auth-service/api/v1/auth/register-verify
    - /auth-service/api/v1/auth/refresh
    - /swagger-ui/**
    - /v3/api-docs/**
    - /swagger-resources/**
    - /webjars/**
    - /auth-service/swagger-ui/**
    - /auth-service/v3/api-docs/**
    - /auth-service/swagger-resources/**
    - /auth-service/webjars/**
    - /user-service/swagger-ui/**
    - /user-service/v3/api-docs/**
    - /user-service/swagger-resources/**
    - /user-service/webjars/**
    - /user-service/api/v1/users/check-phone
    - /movie-service/swagger-ui/**
    - /movie-service/v3/api-docs/**
    - /movie-service/swagger-resources/**
    - /movie-service/webjars/**
    - /movie-service/api/v1/ratings/movies/*
    - /media-service/swagger-ui/**
    - /media-service/v3/api-docs/**
    - /media-service/swagger-resources/**
    - /media-service/webjars/**
    - /cinema-service/swagger-ui/**
    - /cinema-service/v3/api-docs/**
    - /cinema-service/swagger-resources/**
    - /cinema-service/webjars/**
    - /booking-service/swagger-ui/**
    - /booking-service/v3/api-docs/**
    - /booking-service/swagger-resources/**
    - /booking-service/webjars/**
    - /content-service/swagger-ui/**
    - /content-service/v3/api-docs/**
    - /content-service/swagger-resources/**
    - /content-service/webjars/**
    - /communication-service/swagger-ui/**
    - /communication-service/v3/api-docs/**
    - /communication-service/swagger-resources/**
    - /communication-service/webjars/**
    - /booking-service/api/v1/sepay/**
    - /movie-service/api/v1/movies/coming-soon
    - /movie-service/api/v1/movies/showing
    - /content-service/api/v1/banners/active
    - /media-service/api/v1/media/url
    - /movie-service/api/v1/movies/fetch/**
    - /cinema-service/api/v1/showtime/movie/**
    - /cinema-service/api/v1/cinemas/active
    - /communication-service/api/v1/chat-bot
    - /communication-service/api/v1/chat-messages/history/*
    - /movie-service/api/v1/movies/*/similar
    - /movie-service/actuator/**
    - /cinema-service/actuator/**
    - /auth-service/actuator/**
    - /user-service/actuator/**
    - /booking-service/actuator/**
    - /media-service/actuator/**
    - /content-service/actuator/**
    - /communication-service/actuator/**