name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Lấy code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Cài Java 21
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build toàn bộ project từ root pom.xml
      - name: Build all modules
        run: mvn clean package -DskipTests

      # 4️⃣ Đăng nhập Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      # 5️⃣ Build và push Docker image từng service
      - name: Build and Push Docker images
        run: |
          services=(api-gateway auth-service user-service movie-service booking-service cinema-service communication-service content-service discovery-server media-service)
          for service in "${services[@]}"; do
            IMAGE_NAME=${{ secrets.DOCKERHUB_USER }}/$service
            echo "Building and pushing $IMAGE_NAME"
            docker build -t $IMAGE_NAME:latest $service
            docker push $IMAGE_NAME:latest
          done