name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          api-gateway,
          auth-service,
          user-service,
          movie-service,
          booking-service,
          cinema-service,
          communication-service,
          content-service,
          discovery-server,
          media-service
        ]

    steps:
      # 1️⃣ Lấy mã nguồn
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Cài Java 21
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build từng service
      - name: Build ${{ matrix.service }}
        run: mvn -f ${{ matrix.service }}/pom.xml clean package -DskipTests

      # 4️⃣ Đăng nhập Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      # 5️⃣ Build và Push image lên Docker Hub
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USER }}/${{ matrix.service }}
          docker build -t $IMAGE_NAME:latest ${{ matrix.service }}
          docker push $IMAGE_NAME:latest